security:
    encoders:
        AppBundle\Entity\User:
            bcrypt
            #algorithm: sha512
            #encode_as_base64: false
            #iterations: 1000

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        
    providers:
        database_users:
            entity: { class: AppBundle:User, property: username }
        database_admins:
            entity: { class: AppBundle:Admin, property: username }

    firewalls:
        # デバッグツールバーのセキュリティを無効
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/login
            security: false
            
        secured_area:
            pattern: ^/
            anonymous: true
            form_login:
                login_path: security_login_form
                check_path: security_login_check
                post_only: true
                
                # ログイン成功後のリダイレクトオプション。
                always_use_default_target_path: true
                default_target_path:            /
                #target_path_parameter:          _target_path
                #use_referer:                    true

                # ログイン失敗後のリダイレクトオプション。
                failure_path:                   /login
                failure_forward:                false

                # ユーザ名とパスワードフィールドの名前
                username_parameter:             _username
                password_parameter:             _password

                # csrf トークンオプション
                csrf_parameter:                 _csrf_token
                #intention:                      authenticate
                #csrf_token_generator: security.csrf.token_manager

            logout:
                path: security_logout
                target: /login

    #access_control:
        # this is a catch-all for the admin area
        # additional security lives in the controllers
        #- { path: ^/, roles: ROLE_USER }
        #- { path: ^/admin, roles: ROLE_ADMIN }
